---

- name: restart firewalld
  service: name=firewalld state=restarted

- name: wait for firewalld to restart
  pause: seconds=2

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload php-fpm
  service: name=php-fpm state=restarted

- name: restart php-fpm
  service: name=php-fpm state=restarted
